# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f566431f54bd375bfe79c12a732d21ef79ca91286591686790f3f104127c77356c575dcfec7bf0e8f0d80bea0ec08a7045d15a63ee5dafbe77518e1b3e2b265b

test:
  secret_key_base: b206844d892a6e66ebeca1d17d75c37eabed7643404a73dcdbb31c4ecbe393faaefe0ea53cecedea9fa75d3c7922234de40ec8489b9f72ea65c9d5070a277910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
