# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 516b2f1403968c2b12ee3ed6791ac91df9beafeb4df1d8e667c1cd41338a2e49a3b6dc7e50bbe8cdbf7e2da9e3837e53d7f71897bbf69f0cfe19227d57dd766f

test:
  secret_key_base: 76dbb14a8673e7d3957e0088efd127a6fdce9e0a6ec0eb5e3a7d2adf1b85fb69c78d7febcdc0e28674f25338c98aa1335117d67e88bc595baba4d5175cf42836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
