# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d089a0a2af44f4f41ed299eee8e4e834cef5efea0d0051df96625e364c7a432ebf613a07fc799ec0818fbd5fcb26b75ee20a0c9480c90b26661a6463d517b7d

test:
  secret_key_base: 46e98d0382364634230ad50e13781b6e4145a17126615d7edeb5d473b6da531873f8126c3911e3d2db61a883840ab85b3e5be750c7294b3bc8a65bdf4fc56b6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
